const expectedListingsData = [
  {
    errorMessage: "Could not get data from url.",
    url: "https://www.airbnb.co.uk/rooms/33571268",
  },
  {
    amenities: [
      "Suitable for events",
      "Indoor fireplace",
      "Heating",
      "Smoke alarm",
      "Fire extinguisher",
      "First aid kit",
      "Kitchen",
      "Refrigerator",
      "Cooking basics",
      "Oven",
      "Patio or balcony",
      "BBQ grill",
      "Free parking on premises",
      "Hot tub",
      "Host greets you",
    ],
    numberOfBathrooms: 1,
    numberOfBedrooms: 1,
    propertyName: "Little Country Houses - Poppy's Pad",
    propertyType: "Tiny house",
    url: "https://www.airbnb.co.uk/rooms/20669368",
  },
  {
    amenities: [
      "Hair dryer",
      "Shampoo",
      "Body soap",
      "Shower gel",
      "Hot water",
      "Essentials",
      "Hangers",
      "Bed linen",
      "Portable fans",
      "Heating",
      "Smoke alarm",
      "Carbon monoxide alarm",
      "Wifi",
      "Microwave",
      "Mini fridge",
      "Kettle",
      "Wine glasses",
      "Coffee",
      "Private entrance",
      "Free parking on premises",
    ],
    numberOfBathrooms: 1,
    numberOfBedrooms: 1,
    propertyName: "Lovely loft on the beautiful North Norfolk Coast",
    propertyType: "Entire guest house",
    url: "https://www.airbnb.co.uk/rooms/50633275",
  },
];

module.exports = { expectedListingsData };
